// types/wilayas.ts
export const WILAYAS: { name: string; code: string }[] = [
  { name: 'Adrar', code: '01' },
  { name: 'Chlef', code: '02' },
  { name: 'Laghouat', code: '03' },
  { name: 'Oum El Bouaghi', code: '04' },
  { name: 'Batna', code: '05' },
  { name: 'Béjaïa', code: '06' },
  { name: 'Biskra', code: '07' },
  { name: 'Béchar', code: '08' },
  { name: 'Blida', code: '09' },
  { name: 'Bouira', code: '10' },
  { name: 'Tamanrasset', code: '11' },
  { name: 'Tébessa', code: '12' },
  { name: 'Tlemcen', code: '13' },
  { name: 'Tiaret', code: '14' },
  { name: 'Tizi Ouzou', code: '15' },
  { name: 'Alger', code: '16' },
  { name: 'Djelfa', code: '17' },
  { name: 'Jijel', code: '18' },
  { name: 'Sétif', code: '19' },
  { name: 'Saïda', code: '20' },
  { name: 'Skikda', code: '21' },
  { name: 'Sidi Bel Abbès', code: '22' },
  { name: 'Annaba', code: '23' },
  { name: 'Guelma', code: '24' },
  { name: 'Constantine', code: '25' },
  { name: 'Médéa', code: '26' },
  { name: 'Mostaganem', code: '27' },
  { name: 'M’Sila', code: '28' },
  { name: 'Mascara', code: '29' },
  { name: 'Ouargla', code: '30' },
  { name: 'Oran', code: '31' },
  { name: 'El Bayadh', code: '32' },
  { name: 'Illizi', code: '33' },
  { name: 'Bordj Bou Arreridj', code: '34' },
  { name: 'Boumerdès', code: '35' },
  { name: 'El Tarf', code: '36' },
  { name: 'Tindouf', code: '37' },
  { name: 'Tissemsilt', code: '38' },
  { name: 'El Oued', code: '39' },
  { name: 'Khenchela', code: '40' },
  { name: 'Souk Ahras', code: '41' },
  { name: 'Tipaza', code: '42' },
  { name: 'Mila', code: '43' },
  { name: 'Aïn Defla', code: '44' },
  { name: 'Naama', code: '45' },
  { name: 'Aïn Témouchent', code: '46' },
  { name: 'Ghardaïa', code: '47' },
  { name: 'Relizane', code: '48' },
  { name: 'Timimoun', code: '49' },
  { name: 'Bordj Badji Mokhtar', code: '50' },
  { name: 'Ouled Djellal', code: '51' },
  { name: 'Béni Abbès', code: '52' },
  { name: 'In Salah', code: '53' },
  { name: 'In Guezzam', code: '54' },
  { name: 'Touggourt', code: '55' },
  { name: 'Djanet', code: '56' },
  { name: 'El M’Ghair', code: '57' },
  { name: 'El Menia', code: '58' },
];
