# Generated by Django 5.2.7 on 2025-10-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncier',
            name='code',
            field=models.CharField(blank=True, help_text='Exemple: ALG0001_25', max_length=20, null=True, unique=True),
        ),
    ]
