# Generated by Django 5.2.7 on 2025-10-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_foncier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncier',
            name='commune_code',
            field=models.CharField(blank=True, help_text='Code de la commune (ex: 1001)', max_length=20, null=True),
        ),
    ]
