# Generated by Django 5.2.7 on 2025-10-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_foncier_commune_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foncier',
            name='commune_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
