# Generated by Django 5.2.7 on 2025-10-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_foncier_commune_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foncier',
            name='commune_code',
        ),
        migrations.AddField(
            model_name='foncier',
            name='commune',
            field=models.CharField(blank=True, help_text='Code de la commune (ex: 1001)', max_length=20, null=True, unique=True),
        ),
    ]
