# Generated by Django 5.2.7 on 2025-10-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='message1',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
