# Generated by Django 5.2.7 on 2025-10-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_message1_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message1',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AlterField(
            model_name='message1',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
