# Generated by Django 5.2.7 on 2025-10-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_message1_file_alter_message1_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message1',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chatfiles/'),
        ),
    ]
