# Generated by Django 5.2.7 on 2025-11-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_message1_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(choices=[('ouest', 'Ouest'), ('centre', 'Centre'), ('est', 'Est'), ('sud_est', 'Sud-Est'), ('sud_ouest', 'Sud-Ouest'), ('grand_sud', 'Grand Sud')], default='centre', max_length=20),
        ),
    ]
