# Generated by Django 5.2.7 on 2025-11-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncier',
            name='usage',
            field=models.CharField(blank=True, choices=[('lgmts', 'Logements'), ('equip', 'Equipements'), ('aapi', 'AAPI'), ('autre', 'Autre')], max_length=20, null=True),
        ),
    ]
