# Generated by Django 5.2.7 on 2025-11-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_foncier_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncier',
            name='progress_viabilisation',
            field=models.IntegerField(blank=True, help_text='Pourcentage de viabilisation (0-100%)', null=True),
        ),
        migrations.AlterField(
            model_name='foncier',
            name='usage',
            field=models.CharField(blank=True, choices=[('lgmts', 'Logements'), ('equip', 'Equipements'), ('aapi', 'AAPI'), ('promotion', 'Promotion'), ('investissement', 'Investissement'), ('autre', 'Autre')], max_length=20, null=True),
        ),
    ]
