# Generated by Django 5.2.7 on 2025-11-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_foncier_progress_viabilisation_alter_foncier_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foncier',
            name='commune',
            field=models.CharField(blank=True, help_text='Code de la commune (ex: 1001)', max_length=20, null=True),
        ),
    ]
