# Generated by Django 5.2.7 on 2025-11-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_historique'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_see_historique',
            field=models.BooleanField(default=True),
        ),
    ]
