# Generated by Django 5.2.7 on 2025-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_can_see_historique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='can_see_historique',
            field=models.BooleanField(default=False),
        ),
    ]
