# Generated by Django 5.2.7 on 2025-11-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profile_can_see_historique'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncier',
            name='date_transmission',
            field=models.DateField(blank=True, help_text='Date de transmission', null=True),
        ),
        migrations.AddField(
            model_name='foncier',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Foncier complété ?'),
        ),
        migrations.AddField(
            model_name='foncier',
            name='is_transmis',
            field=models.BooleanField(default=False, help_text='Foncier transmis ?'),
        ),
        migrations.AddField(
            model_name='foncier',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surface en m²', max_digits=12, null=True),
        ),
    ]
