# Generated by Django 5.2.7 on 2025-11-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_foncier_date_transmission_foncier_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foncier',
            name='title',
        ),
        migrations.AddField(
            model_name='foncier',
            name='POS',
            field=models.CharField(blank=True, help_text='POS', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foncier',
            name='Ref_Cadastre_Ilot',
            field=models.CharField(blank=True, help_text='Référence ilot cadastral', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foncier',
            name='Ref_Cadastre_Section',
            field=models.CharField(blank=True, help_text='Référence section cadastrale', max_length=50, null=True),
        ),
    ]
