# Generated by Django 5.2.7 on 2025-11-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_foncier_title_foncier_pos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foncier',
            name='location',
        ),
    ]
