# Generated by Django 5.2.7 on 2025-11-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_foncier_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncier',
            name='ispublished',
            field=models.BooleanField(default=False, help_text='Foncier publié ?'),
        ),
    ]
