# Generated by Django 5.2.7 on 2025-11-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_foncier_ispublished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foncier',
            old_name='ispublished',
            new_name='is_published',
        ),
    ]
