# Generated by Django 5.2.7 on 2025-12-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_ispublished_foncier_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foncier',
            name='usage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
