# Generated by Django 5.2.7 on 2025-12-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_foncier_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foncier',
            name='usage',
            field=models.CharField(blank=True, choices=[('lgmts', 'Logements'), ('equip', 'Equipements'), ('aapi', 'AAPI'), ('promotion', 'Promotion'), ('investissement', 'Investissement'), ('autre', 'Autre')], max_length=20, null=True),
        ),
    ]
