# Generated by Django 5.2.7 on 2025-12-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_foncier_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncier',
            name='is_favorited',
            field=models.BooleanField(default=False, help_text='Foncier favorited ?'),
        ),
    ]
