# Generated by Django 5.2.7 on 2025-12-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_foncier_is_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
