# Generated by Django 5.2.7 on 2025-12-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_usage_alter_foncier_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foncier',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surface en m²', max_digits=20, null=True),
        ),
    ]
