# Generated by Django 5.2.7 on 2025-12-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_foncier_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foncier',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Surface en m²', max_digits=20, null=True),
        ),
    ]
