# Generated by Django 5.2.7 on 2025-12-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_foncier_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncier',
            name='is_confirmed_by_DCCF',
            field=models.BooleanField(blank=True, help_text='Confirmé par la DCCF ?', null=True),
        ),
        migrations.AddField(
            model_name='foncier',
            name='is_confirmed_by_Domaine',
            field=models.BooleanField(blank=True, help_text='Confirmé par le Domaine ?', null=True),
        ),
        migrations.AddField(
            model_name='foncier',
            name='is_confirmed_by_duac',
            field=models.BooleanField(blank=True, help_text='Confirmé par la DUAC ?', null=True),
        ),
    ]
