# Generated by Django 5.2.7 on 2025-12-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_foncier_is_confirmed_by_dccf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foncier',
            name='commune',
            field=models.CharField(blank=True, help_text='Code de la commune (ex: 1001)', max_length=50, null=True),
        ),
    ]
