# Generated by Django 5.2.7 on 2025-12-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_foncier_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncier',
            name='progress_status',
            field=models.CharField(blank=True, choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], max_length=20, null=True),
        ),
    ]
