# Generated by Django 5.2.7 on 2025-12-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_foncier_progress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='abrv_str',
            field=models.CharField(blank=True, choices=[('DG', 'DG'), ('DGA', 'DGA'), ('DAF', 'DAF'), ('DFC', 'DFC'), ('DRHM', 'DRHM'), ('SRH', 'SRH'), ('SCPT', 'SCPT'), ('SMGX', 'SMGX'), ('SINF', 'SINF'), ('DP', 'DP'), ('DP-PROSP', 'DP-PROSP'), ('DP-MOB', 'DP-MOB'), ('SPROSP', 'SPROSP'), ('SSIG', 'SSIG'), ('SJUR', 'SJUR'), ('SPFON', 'SPFON'), ('DGF', 'DGF'), ('DGF-MO', 'DGF-MO'), ('DFUR', 'DFUR'), ('DGF-PF', 'DGF-PF'), ('SEREA', 'SEREA'), ('SMAR', 'SMAR'), ('SCOM', 'SCOM'), ('SINV', 'SINV'), ('DRC', 'DRC'), ('DRO', 'DRO'), ('DRE', 'DRE'), ('DRGS', 'DRGS'), ('DRSO', 'DRSO'), ('DRSE', 'DRSE'), ('DPC', 'DPC'), ('SPROSPC', 'SPROSPC'), ('SSIGC', 'SSIGC'), ('DPMC', 'DPMC'), ('SJURC', 'SJURC'), ('SPFONC', 'SPFONC'), ('DMOC', 'DMOC'), ('SEREAC', 'SEREAC'), ('SMARC', 'SMARC'), ('DPO', 'DPO'), ('SPROSPO', 'SPROSPO'), ('SSIGO', 'SSIGO'), ('DPMO', 'DPMO'), ('SJURO', 'SJURO'), ('SPFONO', 'SPFONO'), ('DMOO', 'DMOO'), ('SEREAO', 'SEREAO'), ('SMARO', 'SMARO'), ('DPE', 'DPE'), ('SPROSPE', 'SPROSPE'), ('SSIGE', 'SSIGE'), ('DPME', 'DPME'), ('SJURE', 'SJURE'), ('SPFONE', 'SPFONE'), ('DMOE', 'DMOE'), ('SEREAAE', 'SEREAAE'), ('SMARE', 'SMARE'), ('DPGS', 'DPGS'), ('SPROSPGS', 'SPROSPGS'), ('SSIGGS', 'SSIGGS'), ('DPMGS', 'DPMGS'), ('SJURGS', 'SJURGS'), ('SPFONGS', 'SPFONGS'), ('DMOGS', 'DMOGS'), ('SEREAGS', 'SEREAGS'), ('SMARGS', 'SMARGS'), ('DPSO', 'DPSO'), ('SPROSPSO', 'SPROSPSO'), ('SSIGSO', 'SSIGSO'), ('DPMSO', 'DPMSO'), ('SJURSO', 'SJURSO'), ('SPFONSO', 'SPFONSO'), ('DMOSO', 'DMOSO'), ('SEREASO', 'SEREASO'), ('SMARSO', 'SMARSO'), ('DPSE', 'DPSE'), ('SPROSPSE', 'SPROSPSE'), ('SSIGSE', 'SSIGSE'), ('DPMSE', 'DPMSE'), ('SJURSE', 'SJURSE'), ('SPFONSE', 'SPFONSE'), ('DMOSE', 'DMOSE'), ('SEREAE', 'SEREAE'), ('SMARSE', 'SMARSE'), ('SF', 'SF')], max_length=20, null=True),
        ),
    ]
