# Generated by Django 5.2.7 on 2025-12-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_profile_abrv_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncier',
            name='region',
            field=models.CharField(blank=True, choices=[('DRC', 'Direction Régionale Centre'), ('DRE', 'Direction Régionale Est'), ('DRO', 'Direction Régionale Ouest'), ('DRGS', 'Direction Régionale Sud'), ('DRSE', 'Direction Régionale Sud-Est'), ('DRSO', 'Direction Régionale Sud-Ouest'), ('DG', 'Direction Générale')], max_length=5, null=True),
        ),
    ]
