# Generated by Django 5.2.7 on 2025-12-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_foncier_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('DRC', 'Centre'), ('DRE', 'Est'), ('DRO', 'Ouest'), ('DRSE', 'Sud-Est'), ('DRSO', 'Sud-Ouest'), ('DRGS', 'Grand Sud'), ('DG', 'Direction Générale')], default='centre', max_length=20),
        ),
    ]
