# Generated by Django 5.2.7 on 2026-01-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_profile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncier',
            name='mode',
            field=models.CharField(choices=[('lecture', 'Lecture seule'), ('ecriture', 'Lecture & écriture')], default='lecture', help_text="Mode d'accès au foncier (lecture / écriture)", max_length=10),
        ),
    ]
